# Generated by Django 5.0.7 on 2025-09-26 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aps_urn', models.CharField(blank=True, default='', max_length=512, verbose_name='URN do modelo (APS/Tandem)')),
                ('tandem_twin_id', models.CharField(blank=True, default='', max_length=256, verbose_name='Tandem Twin ID (opcional)')),
                ('tandem_project_id', models.CharField(blank=True, default='', max_length=256, verbose_name='Tandem Project ID (opcional)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
